# Generated by Django 5.2.7 on 2025-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_integration', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
