# Generated by Django 5.0.2 on 2025-11-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_integration', '0003_activity_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('loaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date']},
        ),
    ]
