# Generated by Django 5.2.4 on 2025-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_integration', '0004_missingactivity_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='start_date_local',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingactivity',
            name='start_date_local',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
