# Generated by Django 5.0.2 on 2025-11-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_integration', '0005_activity_start_date_local_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='average_heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
