# Generated by Django 5.2.4 on 2025-11-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava_integration', '0006_alter_activity_options_activity_average_heartrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='timezone',
        ),
    ]
