apiVersion: 1

datasources:
  - name: Stravagancia
    uid: strava-postgres
    type: grafana-postgresql-datasource
    url: ep-wild-sky-al1wjejk.c-3.eu-central-1.aws.neon.tech:5432
    user: neondb_owner
    secureJsonData:
      password: ${NEON_PASSWORD}
    jsonData:
      database: neondb
      sslmode: require
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
